language: node_js
node_js:
- 12.19.0
before_install:
- cd /home/travis/build/richardechegaray/quickPick/backend
- openssl aes-256-cbc -K $encrypted_e6d8f5969085_key -iv $encrypted_e6d8f5969085_iv -in quickpick-7f20f-firebase-adminsdk-hvb4p-96107c2f64.json.enc -out quickpick-7f20f-firebase-adminsdk-hvb4p-96107c2f64.json -d
- npm i -g npm@6.14.8
install:
- npm install
script:
- npm test
